CREATE TABLE IF NOT EXISTS mpa_ratings(
rating_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL);

CREATE TABLE IF NOT EXISTS films(
film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
description varchar(255) NOT NULL,
release_date DATE NOT NULL,
duration int NOT NULL,
rating_id int REFERENCES mpa_ratings(rating_id) NOT NULL);

CREATE TABLE IF NOT EXISTS users(
user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar(255) NOT NULL UNIQUE,
login varchar(255) NOT NULL,
name varchar(255) NOT NULL,
birthday DATE NOT NULL);

CREATE TABLE IF NOT EXISTS genres(
genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL);

CREATE TABLE IF NOT EXISTS films_genres(
genre_id int REFERENCES genres(genre_id) NOT NULL,
film_id int REFERENCES films(film_id) NOT NULL,
CONSTRAINT films_genres_pk PRIMARY KEY (genre_id, film_id));

CREATE TABLE IF NOT EXISTS likes(
user_id int REFERENCES users(user_id) NOT NULL,
film_id int REFERENCES films(film_id) NOT NULL,
CONSTRAINT likes_pk PRIMARY KEY (user_id, film_id));

CREATE TABLE IF NOT EXISTS friends(
user_id int REFERENCES users(user_id) NOT NULL,
friend_id int REFERENCES users(user_id) NOT NULL,
approved BOOLEAN NOT NULL,
CONSTRAINT friends_pk PRIMARY KEY (user_id, friend_id));




